#!name=123云盘
#!desc=过滤123云盘应用端及网页端广告，解除网页端流量1G下载限制（请单文件下载，不要文件夹或多文件下载）。
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md], ddgksf2013[https://github.com/ddgksf2013]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/123Pan-01.png
#!openUrl=https://apps.apple.com/app/id1597682672
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Map Local]
# 横幅广告
^https:\/\/www\.123pan\.com\/api\/config\/get data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
[123云盘]移除广告 = type=http-response, pattern=^https?:\/\/www\.123pan\.com\/s\/[0-9a-zA-Z=_/-]+\.html, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/123pan.js, requires-body=true, timeout=60

[123云盘]解除下载限制 = type=http-request, pattern=^https?:\/\/www\.123pan\.com\/b\/api\/share\/download\/info, script-path=https://raw.githubusercontent.com/ddgksf2013/Scripts/master/123pan.js, timeout=60

[MITM]
hostname = %APPEND% www.123pan.com