#!name=百度网盘
#!desc=过滤百度网盘广告，解锁部分SVIP功能。
#!author=chxm1023[https://github.com/chxm1023], GieGie777[https://t.me/GieGie777], ddgksf2013[https://github.com/ddgksf2013]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/BaiduNetDisk.png
#!openUrl=https://apps.apple.com/app/id547166701
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-01-31 23:00

[Body Rewrite]
http-response-jq ^https:\/\/pan\.baidu\.com\/feed\/kingkongdistrict\? '.data.data |= map(select(.type != "novel" and .type != "shortplay" and .type != "print" and .type != "job_hunt"))'

[Map Local]
# 开屏广告、首页卡片广告、传输页面广告、各类弹窗，精简侧拉抽屉和我的页面
^https:\/\/pan\.baidu\.com\/api\/getconfig\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/api\/getsyscfg\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/api\/taskscore\/tasklist\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/act\/api\/activityentry\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/rest\/\d\.\d\/pcs\/adv\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/api\/plugin\/get\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/pan\.baidu\.com\/recommend\/query\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 启动弹窗
^https?:\/\/.*baidu\.com\/rest\/.*\/membership\/proxy\/guide data-type=text data=" " status-code=200

# 设置信息流
^https?:\/\/pan\.baidu\.com\/act\/v\d\/(bchannel|welfare)\/list data-type=text data=" " status-code=200

# 热搜list
^https:\/\/pan\.baidu\.com\/feed\/hotlist data-type=text data=" " status-code=200

# 活动推广
^https?:\/\/.*zhangyuyidong\.cn\/api\/zysdk data-type=text data=" " status-code=200

# 搜索填词
^https:\/\/pan\.baidu\.com\/queryintent\/queryhint data-type=text data=" " status-code=200

# 金币乐园
^https:\/\/pan\.baidu\.com\/coins\/center\/notice data-type=text data=" " status-code=200

# 短剧
^https:\/\/pan\.baidu\.com\/recommend\/shortseries\/list data-type=text data=" " status-code=200

[Script]
# 广告推广
[百度网盘]移除广告推广@ddgksf2013 = type=http-response, pattern=^https?:\/\/afd\.baidu\.com\/afd\/entry, script-path=https://ddgksf2013.top/scripts/bdpan.ads.js, requires-body=true

# 首页信息流
[百度网盘]移除首页信息流广告@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/feed\/cardinfos, script-path=https://ddgksf2013.top/scripts/bdpan.ads.js, requires-body=true

# 游戏广告
[百度网盘]移除游戏广告@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user\?method=gamecenter, script-path=https://ddgksf2013.top/scripts/bdpan.ads.js, requires-body=true

[百度网盘]倍速播放@ddgksf2013 = type=http-request, pattern=^https:\/\/pan\.baidu\.com\/api\/streaming\?app_id=\d+&type=M3U8_HQ_1080, script-path=https://ddgksf2013.top/scripts/bdpan.unlock.js, requires-body=false

[百度网盘]倍速播放@ddgksf2013 = type=http-response, pattern=^https:\/\/pan\.baidu\.com\/rest\/.*\/membership\/user, script-path=https://ddgksf2013.top/scripts/bdpan.unlock.js, requires-body=true

# chxm1023
[百度网盘]会员权益@chxm1023 = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\/(youai\/(user\/.+\/getminfo|membership\/.+\/adswitch)|(rest\/.+\/membership\/user|act\/.+\/(bchannel|welfare)\/list|api\/usercfg)), script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/bdcloud.js, requires-body=true

# WeiGiegie
[百度网盘]会员权益@WeiGiegie = type=http-response, pattern=^https?:\/\/pan\.baidu\.com\.+(rest\/.+\/membership\/user|api\/user\/getinfo|act\/v2\/welfare\/list|api\/taskscore\/tasklist)\?, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/panda.js, requires-body=true

[MITM]
hostname = %APPEND% pan.baidu.com, afd.baidu.com
