#!name=彩云天气Pro
#!desc=过滤彩云天气广告，解锁SVIP功能。\n解锁功能需App版本低于7.20.2。
#!author=RuCu6[https://github.com/RuCu6], Keywos[https://github.com/Keywos], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/ColorfulCloudsWeatherPro.png
#!openUrl=https://apps.apple.com/app/id1067198688
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Rule]
DOMAIN,abyss.cyapi.cn,REJECT
DOMAIN,ad.cyapi.cn,REJECT
DOMAIN,gather.colorfulclouds.net,REJECT

[Map Local]
^https?:\/\/api\.caiyunapp\.com\/v1\/activity data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/biz\.cyapi\.cn\/(p\/v1\/entries|p\/v1\/trial_card\/info|v2\/product) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/starplucker\.cyapi\.cn\/v3\/(config\/cypage\/\w+\/conditions|notification\/message_center|operation\/homefeatures) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https?:\/\/wrapper\.cyapi\.cn\/v1\/activity\? data-type=file data="https://raw.githubusercontent.com/Keywos/rule/main/mocks/caiyun.json" status-code=200 header="Content-Type:application/json"

[Script]
# 共享会员
[彩云天气]共享会员 = type=http-request, pattern=^https:\/\/wrapper\.cyapi\.cn\/v1\/(nafp\/origin_images|satellite)\?, script-path=https://loon.103516.xyz/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js

[彩云天气]共享会员 = type=http-response, pattern=^https:\/\/biz\.cyapi\.cn\/(api\/v1\/user_detail|p\/v1\/vip_info|v2\/user), script-path=https://loon.103516.xyz/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js, requires-body=true

# 底部菜单栏,活动推广
[彩云天气]移除广告 = type=http-response, pattern=^https:\/\/(wrapper\.cyapi\.cn|api\.caiyunapp\.com|cdn-w\.caiyunapp\.com)\/v1\/activity\?, script-path=https://loon.103516.xyz/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js, requires-body=true

[MITM]
hostname = %APPEND% biz.cyapi.cn, starplucker.cyapi.cn, api.caiyunapp.com, cdn-w.caiyunapp.com, wrapper.cyapi.cn
