#!name=帆书
#!desc=过滤帆书（樊登读书）广告
#!author=Yuheng0101[https://github.com/Yuheng0101]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/Fanshu.png
#!openUrl=https://apps.apple.com/app/id963152777
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[URL Rewrite]
# 帆书移除广告
^https?:\/\/popup\.dushu365\.com\/api\/v2\/sfo\/(user_)?popup_(?:config|display)s - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/chief-orch\/config\/config\/v\d+\/(?:shortCut|appUpdateUnite|loadingAd) - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/fs-retain\/trialVip\/v\d+\/requestTrialVipPopDoNotSendReward - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/resource-orchestration-system\/vipLandingPage\/v\d+\/getVipLandingPageApp - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/fandeng-orch\/dual2211\/config - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/fdtalk-orch\/newcomerzone\/v\d+\/guide - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/fandeng-orch\/bookboy\/v\d+\/vipPagePop - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/chief-orch\/config\/config\/v\d+\/appConfig - reject
^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/order-orchestration\/orderWeb\/exchange\/v100\/showExchangeButton - reject

[Script]
[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/chief-orch\/home\/bookPortal\/v105\/category, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/abtest-front\/banner-modular\/get, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/resource-orchestration-system\/book\/channel\/v100\/info, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/fs-member\/user\/profile\/v100\/detail, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/chief-orch\/home\/bookPortal\/v111\/forApp, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/sns-orchestration-system\/homePage\/api\/v100\/myPage, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/task-orchestration\/taskCenter\/api\/v101\/taskList, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/resource-orchestration-system\/book\/v101\/content, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[帆书]移除广告 = type=http-response, pattern=^https?:\/\/g[a-z0-9-]+\.dushu365\.com\/user-orchestration\/user\/api\/v101\/ceiltip, script-path=https://raw.githubusercontent.com/Yuheng0101/X/main/Scripts/FanShu/No_Ads.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% g*.dushu365.com
