#!name=粉笔
#!desc=过滤粉笔广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/Fenbi.png
#!openUrl=https://apps.apple.com/app/id584660358
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-04-07 11:00

[Body Rewrite]
http-response-jq ^https:\/\/hera-webapp\.fenbi\.com\/(?:iphone|ipad)\/recommend\/info\? 'delpaths([["data","rollingBanner"]])'
http-response-jq ^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/apps\/config\? 'delpaths([["data","bottomIconInfos","position","iconDefaultUrl"]])'
http-response-jq ^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/apps\/config\? 'delpaths([["data","bottomIconInfos","position","iconSelectedUrl"]])'
http-response-jq ^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/apps\/config\? 'delpaths([["data","bottomIconInfos","position","nightModeIconDefaultUrl"]])'
http-response-jq ^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/apps\/config\? 'delpaths([["data","bottomIconInfos","position","nightModeIconSelectedUrl"]])'

[Map Local]
# 开屏广告、弹窗广告、悬浮广告、热门搜索、底栏皮肤、我的页面、AI
^https:\/\/keapi\.fenbi\.com\/app\/(?:iphone|ipad)\/position_resource\/get_banners\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/market-api\.fenbi\.com\/(?:iphone|ipad)\/v1\/assistant\/info\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/keapi\.fenbi\.com\/app\/(?:iphone|ipad)\/position_resource\/get_home_banners\?.*position_resource_type=1 mock-response-body data-type=json data="{"code":1,"msg":"","data":{"positionResourceType":1,"payload":{"items":[{"id":17868,"courseSetId":2,"content":"粉笔-遇见不一样的自己","imageUrl":"https://i.im.ge/evoCrm/FenbiBanner.png","url":"null","redirectType":1,"ordinal":8,"createdTime":1746799144383,"startTime":1759850171000,"endTime":4070880000000,"type":0,"bizType":4}],"count":1}}}" status-code=200

^https:\/\/keapi\.fenbi\.com\/app\/(?:iphone|ipad)\/position_resource\/get_home_banners\?.*position_resource_type=2 data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/keapi\.fenbi\.com\/app\/(?:iphone|ipad)\/\w+\/reddot\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/timetable\/today_with_public_episodes\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/hera-webapp\.fenbi\.com\/(?:iphone|ipad)\/topic\/hotquery\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/hera-webapp\.fenbi\.com\/(?:iphone|ipad)\/explore\/consts\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/hera-webapp\.fenbi\.com\/(?:iphone|ipad)\/announcement\/hotquery\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/user_member\/entry\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/market-api\.fenbi\.com\/(?:iphone|ipad)\/v1\/assistant\/my\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/ke\.fenbi\.com\/(?:iphone|ipad)\/v3\/remind\/instant\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/keapi\.fenbi\.com\/ai\/(?:iphone|ipad)\/exercise_remark\/get_questions_remark\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/keapi\.fenbi\.com\/app\/(?:iphone|ipad)\/position_resource\/get_tiku_banners\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/keapi\.fenbi\.com\/ai\/(?:iphone|ipad)\/entry\? data-type=text data="{"msg":"","data":null,"code":404}" header="Content-Type:application/json"

[MITM]
hostname = %APPEND% keapi.fenbi.com, market-api.fenbi.com, ke.fenbi.com, hera-webapp.fenbi.com
