#!name=iTunes
#!desc=iTunes系列解锁合集，在设置中选择需要使用的原作者脚本以使用此插件。
#!author=chxm1023[https://github.com/chxm1023], ddgksf2013[https://github.com/ddgksf2013], Guding88[https://github.com/Guding88]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/iTunes.png
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-02-18 18:00
#!arguments=iTunes-chxm1023:false,iTunes-ddgksf2013:false,iTunes-Guding88:false

[Script]
# chxm1023
[iTunes]解锁会员@chxm1023 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js, requires-body=true

# ddgksf2013
[iTunes]解锁会员@ddgksf2013 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://loon.103516.xyz/Script/iTunes/iTunes-ddgksf2013.js, requires-body=true

# Guding88
[iTunes]解锁会员@Guding88 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/Guding88/Script/main/APPheji_iTunes.js, requires-body=true

[MITM]
hostname = %APPEND% buy.itunes.apple.com
