#!name=LoonLab Converter
#!desc=本插件依赖Script Hub插件，用于将LoonLab中的Loon插件转换为Surge/Egern/Shadowrocket模块。\n可选目标客户端为 Loon、Surge、Egern、Shadowrocket，默认值为Loon，原插件不做转换。
#!author=sooyaaabo[https://github.com/sooyaaabo]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/Other/LoonLab.png
#!openUrl=https://loonlab.103516.xyz/Plugin/
#!tag=功能增强
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-01-04 11:00
#!arguments=目标客户端:Loon
#!arguments-desc=目标客户端\n- Loon: 保持原插件格式（默认，不转换）\n- Surge: 转换为 Surge 模块\n- Egern: 转换为 Egern 模块\n- Shadowrocket: 转换为 Shadowrocket 模块

[Script]
[LoonLab]Converter = type=http-response, pattern=^https?:\/\/loonlab\.103516\.xyz\/Plugin\/, script-path=https://loon.103516.xyz/Script/LoonLab/LoonLabConverter.js, requires-body=true, argument="{{{目标客户端}}}"

[MITM]
hostname = %APPEND% loonlab.103516.xyz
