#!name=LoonLab Converter
#!desc=本插件依赖Script Hub插件，用于将LoonLab中的Loon插件转换为Surge/Egern/Shadowrocket模块。\n可选目标客户端为 Loon、Surge、Egern、Shadowrocket，默认值为Loon，原插件不做转换。
#!author=sooyaaabo[https://github.com/sooyaaabo]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/Other/LoonLab.png
#!openUrl=https://loonlab.103516.xyz/Plugin/
#!tag=功能增强
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-01-04 11:00
#!arguments=target:"Loon"

[Script]
[LoonLab]Converter = type=http-response, pattern=^https?:\/\/loonlab\.103516\.xyz\/Plugin\/, script-path=https://loon.103516.xyz/Script/LoonLab/LoonLabConverter.js, requires-body=true, argument=[{{{target}}}]

[MITM]
hostname = %APPEND% loonlab.103516.xyz
