#!name=瑞幸咖啡
#!desc=过滤瑞幸咖啡广告
#!author=Sliverkiss[https://github.com/Sliverkiss], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/LuckinCoffee.png
#!openUrl=https://apps.apple.com/app/id1296749505
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[URL Rewrite]
# 日历
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/growUp\/calendarList - reject
# 礼品卡
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/promotion\/giftCard\/topPage - reject
# 幸运集杯横幅
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/sys\/base\/myLittleLuck - reject
# 新人推荐
^https:\/\/capi\.lkcoffee\.com\/resource\/core\/v2\/menu\/ordinaryUserLayeredArea - reject
# 轮播图
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/sys\/common\/modules - reject
# 首页商品列表
^https:\/\/capi\.lkcoffee\.com\/resource\/core\/v2\/homepage\/homePageCoffeeList - reject
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/eorder\/product\/popAppTagProductList - reject
# 开屏广告
^https:\/\/capi\.lkcoffee\.com\/resource\/m\/sys\/app\/adposNew - reject

[MITM]
hostname = %APPEND% capi.lkcoffee.com
