#!name=QQ音乐
#!desc=过滤QQ音乐广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/QQMusic.png
#!openUrl=https://apps.apple.com/app/id414603431
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Rule]
DOMAIN,adstats.tencentmusic.com,REJECT
DOMAIN,ad.tencentmusic.com,REJECT
DOMAIN,adcdn.tencentmusic.com,REJECT
DOMAIN,adcdn6.tencentmusic.com,REJECT
DOMAIN,adexpo.tencentmusic.com,REJECT
DOMAIN,adclick.tencentmusic.com,REJECT
DOMAIN,mc.tencentmusic.com,REJECT
DOMAIN,monitor.music.qq.com,REJECT
DOMAIN,tmead.y.qq.com,REJECT
DOMAIN,tmeadbak.y.qq.com,REJECT
DOMAIN,tmeadquic.y.qq.com,REJECT
