#!name=铁路12306
#!desc=过滤铁路12306广告
#!author=RuCu6[https://github.com/RuCu6], kokoryh[https://github.com/kokoryh]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/Railway12306.png
#!openUrl=https://apps.apple.com/app/id564818797
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-04-17 12:00

[Rule]
# 放行规则
DOMAIN,ad.12306.cn,DIRECT

[Body Rewrite]
http-response-jq ^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$ 'delpaths([["materialsList"]])'
http-response-jq ^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$ 'delpaths([["advertParam"]])'

[Script]
# 移除12306应用内广告
[铁路12306]移除应用内广告 = type=http-request, pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$, script-path=https://kelee.one/Resource/JavaScript/12306/12306_remove_ads.js

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn
