#!name=汽水音乐
#!desc=过滤汽水音乐广告
#!author=可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/SodaMusic.png
#!openUrl=https://apps.apple.com/app/id1605585211
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Body Rewrite]
http-response-jq ^https:\/\/tnc\d-(bjlgy|ali[a-z]{2})\d?\.zijieapi\.com\/get_domains\/v\d\/\? 'if (getpath(["data"]) | has("opaque_data_enabled")) then (setpath(["data","opaque_data_enabled"]; 0)) else . end'
http-response-jq ^https:\/\/tnc\d-(bjlgy|ali[a-z]{2})\d?\.zijieapi\.com\/get_domains\/v\d\/\? 'if (getpath(["data"]) | has("ttnet_http_dns_enabled")) then (setpath(["data","ttnet_http_dns_enabled"]; 0)) else . end'
http-response-jq ^https:\/\/tnc\d-(bjlgy|ali[a-z]{2})\d?\.zijieapi\.com\/get_domains\/v\d\/\? 'if (getpath(["data"]) | has("ttnet_quic_enabled")) then (setpath(["data","ttnet_quic_enabled"]; 0)) else . end'
http-response-jq ^https:\/\/tnc\d-(bjlgy|ali[a-z]{2})\d?\.zijieapi\.com\/get_domains\/v\d\/\? 'if (getpath(["data"]) | has("ttnet_tt_http_dns")) then (setpath(["data","ttnet_tt_http_dns"]; 0)) else . end'
http-response-jq ^https:\/\/tnc\d-(bjlgy|ali[a-z]{2})\d?\.zijieapi\.com\/get_domains\/v\d\/\? '.data.ttnet_dispatch_actions |= map(select(.action != "dispatch" and .action != "tc"))'
http-response-jq ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/me\? 'delpaths([["reward_ad_banner"]])'
http-response-jq # ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/me\/recently-played-media\? '.media |= map(select(.type != "video"))'
http-response-jq ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/feed\/song-tab\? 'del(.items[] | select(.type == "video_track_mix"))'
http-response-jq ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/card\? 'delpaths([["preview_guide"]])'
http-response-jq ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/card\? 'del(.card_items[] | select(has("priority_display")))'
http-response-jq ^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/more-panel\? '.blocks |= map(select(.type != "related_video"))'

[Map Local]
# 追加的销售配置
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.com\/luna\/commerce\/upsells_config\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 广告下发
^https:\/\/(api|api5-lq)\.qishui\.com\/luna\/ads\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.com\/luna\/ads\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 发现页面 - 正在直播Add commentMore actions
^https:\/\/webcast-open\.douyin\.com\/webcast\/openapi\/feed\/\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 签到入口
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/treasure\/entrance\/config\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 搜索页面 - 横幅推广
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/activities\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 播放器 - 视频广告
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/media_ads\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 免费听歌推广
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/commerce\/upsells\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 邀请开通会员弹窗
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/commerce\/v2\/commerce_info\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 抖音看过悬浮窗
^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/listen-video\/reminder\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
# 播放页面 - 视频流[响应体太大]
[汽水音乐]移除播放页面视频流 = type=http-response, pattern=^https:\/\/(beta-luna\.douyin|api5-lq\.qishui)\.douyin\.com\/luna\/me\/recently-played-media\?, script-path=https://kelee.one/Resource/JavaScript/SodaMusic/SodaMusic_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% webcast-open.douyin.com, beta-luna.douyin.com, api.qishui.com, api5-lq.qishui.com, tnc*-*.zijieapi.com
