#!name=腾讯视频
#!desc=不负好时光 [不负好广告]
#!author=RuCu6[https://github.com/RuCu6]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/TencentVideo.png
#!openUrl=https://apps.apple.com/app/id458318329
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Rule]
AND,((IP-CIDR,0.0.0.0/0,no-resolve),(USER-AGENT,"live4iphoneRel*")),REJECT-DROP
DOMAIN,adsmind.gdtimg.com,REJECT
DOMAIN,info4.video.qq.com,REJECT
DOMAIN,info6.video.qq.com,REJECT
DOMAIN,ios.video.mpush.qq.com,REJECT
DOMAIN,otheve.beacon.qq.com,REJECT
DOMAIN,pgdt.gtimg.cn,REJECT
DOMAIN,tpns.qq.com,REJECT
DOMAIN,vv6.video.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-KEYWORD,trace.qq.com,REJECT
DOMAIN-KEYWORD,trace.video.qq.com,REJECT
IP-CIDR,47.110.187.87/32,REJECT,no-resolve
URL-REGEX,"^http:\/\/[\d\.:]*\/?(defaultts\.tc|vmind\.qqvideo\.tc|finderpdd\.video)\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-vlive\.apdcdn\.tc\.qq\.com\/vmind\.qqvideo\.tc\.qq\.com\/\w+",REJECT
URL-REGEX,"^http:\/\/apd-\w+\.v\.smtcdns\.com\/(defaultts|omts|vmind\.qqvideo)\.tc\.qq\.com\/\w+",REJECT
DOMAIN,ugchsy.gtimg.com,REJECT
DOMAIN,rmonitor.qq.com,REJECT
DOMAIN,activity.video.qq.com,REJECT
DOMAIN,iacc.qq.com,REJECT
DOMAIN,tux.qq.com,REJECT
DOMAIN,aegis.qq.com,REJECT
DOMAIN,rdelivery.qq.com,REJECT
DOMAIN-SUFFIX,static-res.qq.com,REJECT
DOMAIN-SUFFIX,gdtimg.com,REJECT
DOMAIN-SUFFIX,l.qq.com,REJECT
DOMAIN-SUFFIX,gdt.qq.com,REJECT
DOMAIN-SUFFIX,video.mpush.qq.com,REJECT
DOMAIN-SUFFIX,api.poll.video.qq.com,REJECT
DOMAIN-SUFFIX,tpns.tencent.com,REJECT
DOMAIN-SUFFIX,omgmta.qq.com,REJECT
DOMAIN-SUFFIX,omgmta1.qq.com,REJECT
DOMAIN-KEYWORD,track.qq.com,REJECT
DOMAIN-KEYWORD,trace.qq.com,REJECT
DOMAIN-KEYWORD,pgdt.gtimg.c,REJECT
DOMAIN-KEYWORD,trace.video.qq.com,REJECT
DOMAIN-KEYWORD,1258344696.file.myqcloud.com,REJECT
IP-CIDR,183.201.213.194/32,REJECT,no-resolve
IP-CIDR,120.222.144.64/32,REJECT,no-resolve
IP-CIDR,111.6.166.107/32,REJECT,no-resolve

[Body Rewrite]
http-request ^https?:\/\/vv\.video\.qq\.com\/getvinfo &sppreviewtype=\d(.*)&spsrt=\d &sppreviewtype=0$1&spsrt=0

[Map Local]
# ^http:\/\/apd-\w+\.v\.smtcdns\.com\/(defaultts|omts|vmind\.qqvideo)\.tc\.qq\.com\/\w+ reject
^https?:\/\/vv\.video\.qq\.com\/(diff|get)vmind data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
# [腾讯视频]移除广告 = type=http-request, pattern=^https?:\/\/vv\.video\.qq\.com\/getvinfo, script-path=https://loon.103516.xyz/Script/CommonScript/replace-body.js, requires-body=true, argument="&sppreviewtype=\d(.*)&spsrt=\d->&sppreviewtype=0$1&spsrt=0"

[MITM]
hostname = %APPEND% vv.video.qq.com
