#!name=微博
#!desc=微博全面净化
#!author=RuCu6[https://github.com/RuCu6], fmz200[https://github.com/fmz200], zmqcherish[https://github.com/zmqcherish], neishe321[https://github.com/neishe321], 可莉🅥[https://github.com/luestr/ProxyResource/blob/main/README.md]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/Weibo.png
#!openUrl=https://apps.apple.com/app/id350962117
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2026-02-22 09:00
#!arguments=MainTabFilter:true

[Rule]
# 收集用户信息，上传用户日志的请求
URL-REGEX,"^https?:\/\/m?api\.weibo\.c(n|om)\/2\/(push\/active|client\/addlog_batch|ad\/preload)",REJECT-DROP
URL-REGEX,"^https?:\/\/api-cloudim\.api\.weibo\.com\/v1\/log\/",REJECT-DROP
# 微博开屏广告
DOMAIN-SUFFIX,biz.weibo.com,REJECT
DOMAIN,bootpreload.uve.weibo.com,REJECT
# 其他广告
DOMAIN-SUFFIX,fastimage.uve.weibo.com,REJECT
DOMAIN-SUFFIX,adimg.vue.weibo.com,REJECT
DOMAIN-SUFFIX,zymo.mps.weibo.com,REJECT
DOMAIN-SUFFIX,weibomingzi.com,REJECT
DOMAIN-SUFFIX,sdkapp.uve.weibo.com,REJECT
DOMAIN-SUFFIX,promote.biz.weibo.cn,REJECT
DOMAIN-SUFFIX,gw5.push.mcp.weibo.cn,REJECT
DOMAIN-SUFFIX,gw6.push.mcp.weibo.cn,REJECT
DOMAIN-SUFFIX,game.weibo.cn,REJECT
DOMAIN-SUFFIX,adimg.uve.weibo.com,REJECT
DOMAIN-SUFFIX,game.weibo.com,REJECT
DOMAIN-SUFFIX,ads.viber.com,REJECT
DOMAIN-SUFFIX,ads-d.viber.com,REJECT
DOMAIN-SUFFIX,ads.aws.viber.com,REJECT
DOMAIN-SUFFIX,alitui.weibo.com,REJECT
DOMAIN-SUFFIX,dp.im.weibo.cn,REJECT
DOMAIN-SUFFIX,biz.weibo.com.cn,REJECT
DOMAIN-SUFFIX,click.uve.weibo.com,REJECT
DOMAIN-SUFFIX,wax.weibo.com,REJECT
DOMAIN-SUFFIX,wbapp.uve.weibo.com,REJECT
DOMAIN-SUFFIX,widget.weibo.com,REJECT
DOMAIN-SUFFIX,dsp.edm.weibo.cn,REJECT
DOMAIN-SUFFIX,alitui.weibo.com.cn,REJECT
DOMAIN-SUFFIX,tui.weibo.com,REJECT
DOMAIN-SUFFIX,wax.weibo.com.cn,REJECT
DOMAIN-SUFFIX,ad.weibo.com,REJECT
# 屏蔽信息收集
DOMAIN,datacollection.uve.weibo.com,REJECT
DOMAIN,adpinpai.video.weibocdn.com,REJECT

[URL Rewrite]
# 微博
^https?:\/\/m?api\.weibo\.c(n|om)\/2\/logservice\/service\? - reject

[Body Rewrite]
http-response-jq ^https:\/\/m?api\.weibo\.c(n|om)\/2\/cardlist\? 'del(.items[] | select(.category == "group"))'

[Map Local]
# 首页 - 签到、发布按钮、侧边栏、右上角红包、顶部标签页、侧边栏提醒、超话标签页悬浮、顶部直播
^https:\/\/m?api\.weibo\.c(n|om)\/2\/(?:ug\/checkin\/list|push\/daily|push\/info) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/live\/media_homelist\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 详情页 - 超话、评论区、看图界面、个人主页、我的页面、信息流、商品橱窗、视频流、视频号、视频调查、话题卡片
^https:\/\/m?api\.weibo\.c(n|om)\/2\/comments\/bullet_screens\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/photo\/info\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/(?:container_positive|push_info) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/vote\/get_vote_detail\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/chaohua\/discovery\/home_bottom\/switch\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/huati\/(?:discovery_home_bottom_channels|discovery_home_bottom_getdotinfo|mobile_discovery_searchchange) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/wbox\/\w+\/(?:home_bottom_modal|interest_category) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 发现页 - 热门微博信息流、搜索列表、热搜提醒、猜你想搜、视频流红包
^https:\/\/m?api\.weibo\.c(n|om)\/2\/search\/(?:container_discover|finder_nav_polling)\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/hot\/hours_spotlight\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/video\/redpacket\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/(?:search\/finder_nav_polling|sug\/list\/finderchange|was\/finder\/searchbarchange)\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 视频页
^https:\/\/m?api\.weibo\.c(n|om)\/2\/video\/tiny_video_info_show\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 开屏广告 //*.uve.weibo.com
^https:\/\/(?:bootrealtime|bootpreload)\.uve\.weibo\.com\/v\d\/ad\/(?:realtime|preload) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/sdkapp\.uve\.weibo\.com\/interface\/sdk\/(?:get-lbs-cell-info\.php|sdkconfig\.php) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

# 微博长文章推广
^https:\/\/card\.weibo\.com\/article\/m\/aj\/(?:reward|uvead) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

^https:\/\/weibo\.com\/ttarticle\/x\/m\/aj\/(?:reward|uvead) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
# 发现页
[微博]发现页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/search\/(finder|container_timeline|container_discover)\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 热搜页
[微博]热搜页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/(page|flowpage)\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 话题页
[微博]话题页面 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/searchall\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 超话页
[微博]超话页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/container_timeline_topicpage\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 超话Tab页
[微博]超话Tab页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/container_timeline_topic\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 详情页
[微博]详情页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/extend\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

[微博]详情页 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/container_detail\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 顶部Tab页分组
[微博]顶部Tab页分组 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/groups\/allgroups\/v2\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 评论区
[微博]评论区 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/comments\/mix_comments\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

[微博]评论区 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/(container_detail_comment|container_detail_mix)\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

# 转发区
[微博]转发区 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/container_detail_forward\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_ads.js, requires-body=true, timeout=60

[微博]转发区 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/statuses\/repost_timeline\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_main.js, requires-body=true, timeout=60

# 其余广告及各部分推广 - cherish
[微博]其余广告及各部分推广 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)/2/(cardlist|searchall|page|messageflow|statuses/(unread_)?friends(/|_)timeline|groups/timeline|statuses/(container_timeline|container_timeline_hot|unread_hot_timeline|extend|video_mixtimeline)|profile/(me|container_timeline)|video/(community_tab|remind_info|tiny_stream_video_list)|checkin/show|(\!/)?live/media_homelist|comments/build_comments|container/get_item)\?, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/weibo/weibo_main.js, requires-body=true, timeout=60

[微博]其余广告及各部分推广 = type=http-response, pattern=^https?:\/\/(sdk|wb)app\.uve\.weibo\.com(/interface/sdk/sdkad.php|/wbapplua/wbpullad.lua)\?, script-path=https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo_launch.js, requires-body=true, timeout=60

# 自定义Tab皮肤
[微博]自定义Tab皮肤 = type=http-response, pattern=^https:\/\/m?api\.weibo\.c(n|om)\/2\/!\/client\/light_skin\?, script-path=https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo_main.js, requires-body=true, timeout=60

# 非会员设置Tab皮肤 - cherish
[微博]非会员设置Tab皮肤 = type=http-response, pattern=^https:\/\/new\.vip\.weibo\.c(n|om)\/littleskin\/preview\?, script-path=https://raw.githubusercontent.com/zmqcherish/proxy-script/main/weibo_main.js, requires-body=true, timeout=60

# 会员图标
[微博]会员图标 = type=http-response, pattern=^https:\/\/new\.vip\.weibo\.c(n|om)\/aj\/appicon\/list\?, script-path=https://github.com/fmz200/wool_scripts/raw/main/Scripts/weibo/weibo_vip.js, requires-body=true, timeout=60

[MITM]
hostname = %APPEND% *.weibo.cn, *.weibo.com, weibo.com
