#!name=XPTV
#!desc=伪CMS源，安装此插件后在XPTV内添加订阅地址：https://ykusu.ykusu/getJSON/cmsbeta.json
#!author=Yswag[https://github.com/Yswag]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/XPTV.png
#!openUrl=https://apps.apple.com/app/id6459409368
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30

[Script]
[XPTV]XPTV-sources = type=http-request, pattern=^https?:\/\/ykusu\.ykusu\/(.*)\/provide\/vod, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/spider.js

[XPTV]XPTV-getJSON = type=http-request, pattern=^https?:\/\/ykusu\.ykusu\/getJSON\/(.*).json, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/spider.js

[XPTV]美剧星球 = type=http-response, pattern=^https:\/\/tencent-1257389134\.cos\.ap-nanjing\.myqcloud\.com\.qqhd\.net\/fangdao\.php, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]短剧天堂 = type=http-request, pattern=^https:\/\/api\.emasmr\.com.*mp4, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]速讯影院 = type=http-response, pattern=^https?:\/\/hd\.suxun\.site\/api\.php\/provide\/vod(.*)&ids, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]文才资源 = type=http-request, pattern=^https?:\/\/ppvod01\.blbtgg\.com.*(ts|m3u8), script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]MGTV = type=http-response, pattern=^https?:\/\/vipcj\.timizy\.top\/api\.php\/provide\/vod\/from\/mgtv(.*)&ids, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]dsakf23665 = type=http-response, pattern=^https?:\/\/dsakf23665\.com\/api\.php\/provide\/vod(.*)&ids, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[XPTV]JX = type=http-response, pattern=^https:\/\/42\.157\.129\.29:2222\/.*\.png, script-path=https://raw.githubusercontent.com/Yswag/for-own-use/main/XPTV/spider/xptv-misc.js, requires-body=true, timeout=10

[MITM]
hostname = %APPEND% ykusu.ykusu, tencent-1257389134.cos.ap-nanjing.myqcloud.com.qqhd.net, api.emasmr.com, ppvod01.blbtgg.com, vipcj.timizy.top, 42.157.129.29:2222
