#!name=Youtube (Music)
#!desc=过滤Youtube (Music)广告，增加画中画、字幕翻译、歌词翻译功能，支持后台播放。需要启用QUIC回退保护。不支持tvOS设备。
#!author=Maasea[https://github.com/Maasea], VirgilClyne[https://github.com/VirgilClyne], Choler[https://github.com/Choler], DivineEngine[https://github.com/DivineEngine], app2smile[https://github.com/app2smile], ddgksf2013[https://github.com/ddgksf2013]
#!icon=https://raw.githubusercontent.com/sooyaaabo/IconLibrary/main/App/YouTube.png
#!openUrl=https://apps.apple.com/app/id544007664
#!homepage=https://github.com/sooyaaabo/Egern
#!date=2025-12-29 16:30
#!arguments=blockUpload:true,blockShorts:true,blockImmersive:true,captionLang:"zh-Hans",lyricLang:"zh-Hans",debug:false

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,QUIC)),REJECT
AND,((DOMAIN-SUFFIX,youtubei.googleapis.com),(PROTOCOL,QUIC)),REJECT

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data=" " status-code=200

[Script]
[YouTube]响应Respone = type=http-response, pattern=^https:\/\/youtubei\.googleapis\.com\/(youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch))(\?(.*))?$, script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js, requires-body=true, binary-body-mode=true, argument="[{{{blockUpload}}},{{{blockShorts}}},{{{blockImmersive}}},{{{captionLang}}},{{{lyricLang}}},{{{debug}}}]"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
